open-policy-agent/frameworks

constraint/Dockerfile, constraint/Makefile, constraint/tests/test_remote_driver.sh
This should allow us to run `make hermetic_test` to run all tests, including those requiring side-processes.
=> Hermetic test

constraint/README.md, constraint/config/crds/templates_v1alpha1_constrainttemplate.yaml, constraint/pkg/apis/templates/v1alpha1/constrainttemplate_types.go, constraint/pkg/apis/templates/v1alpha1/zz_generated.deepcopy.go, constraint/pkg/client/client.go, constraint/pkg/client/client_test.go, constraint/pkg/client/crd_helpers_test.go, constraint/pkg/client/e2e_tests.go
Maps are disfavored compared to lists:
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#lists-of-named-subobjects-preferred-over-maps
Not using a "name" field because we may want to have multiple targets in the future.
=> Update target field to comply with KRM conventions

constraint/pkg/client/client.go, constraint/pkg/client/client_test.go
Signed-off-by: Craig Tabita <ctab@google.com>
=> New UnrecognizedContraintError to allow type introspection

constraint/pkg/client/client.go, constraint/pkg/client/client_test.go, constraint/pkg/client/e2e_tests.go
Fixes https://github.com/open-policy-agent/gatekeeper/issues/156
=> fix CT name validation

constraint/Gopkg.lock, constraint/config/crds/templates_v1alpha1_constrainttemplate.yaml, constraint/pkg/apis/templates/v1alpha1/constrainttemplate_types.go, constraint/pkg/client/client.go, constraint/pkg/client/client_test.go, constraint/pkg/client/e2e_tests.go, constraint/pkg/client/regolib/src.go, constraint/pkg/client/test_handler.go, constraint/vendor/github.com/open-policy-agent/opa/ast/builtins.go, constraint/vendor/github.com/open-policy-agent/opa/ast/compare.go, constraint/vendor/github.com/open-policy-agent/opa/ast/compile.go, constraint/vendor/github.com/open-policy-agent/opa/ast/term.go, constraint/vendor/github.com/open-policy-agent/opa/topdown/arithmetic.go, constraint/vendor/github.com/open-policy-agent/opa/topdown/array.go, constraint/vendor/github.com/open-policy-agent/opa/topdown/builtins/builtins.go, constraint/vendor/github.com/open-policy-agent/opa/topdown/cidr.go, constraint/vendor/github.com/open-policy-agent/opa/topdown/eval.go, constraint/vendor/github.com/open-policy-agent/opa/topdown/http.go
Fixes https://github.com/open-policy-agent/gatekeeper/issues/153
=> handle namespaceselector and empty namespaces

constraint/pkg/client/client.go
=> Move arity check to Create CRD to allow wrong-arity to fail faster

constraint/config/crds/templates_v1alpha1_mutationtemplate.yaml, constraint/pkg/apis/templates/v1alpha1/mutationtemplate_types.go, constraint/pkg/apis/templates/v1alpha1/mutationtemplate_types_test.go, constraint/pkg/client/client.go, constraint/pkg/client/crd_helpers.go, constraint/pkg/client/crd_helpers_test.go
Refactored OPA client code and introduced a few Mutation variants of Client functions to allow them to accept MutationTemplates and then build appropriate Mutation CRD Go objects. Tested mainly with `go test` at the package level, and then later copying diffs into a new Gatekeeper image and running that on a GKE cluster.
=> Allow for the creation of MutationCRDs alongside Constraint CRDs

constraint/Dockerfile
Shaved 300+ MB from docker image:
dmitrytokarev/opa-frameworks                untrimmed                  4849ca580d5e        3 minutes ago       1.45GB
dmitrytokarev/opa-frameworks                trimmed                    1cda21aef183        6 minutes ago       1.12GB
To further reduce size I propose using `FROM golang:1.10.3-alpine` it will reduce size by ~500 MB:
golang                                      1.10.3-alpine              cace225819dc        14 months ago       259MB
golang                                      1.10.3                     d0e7a411e3da        15 months ago       794MB
=> Cleaned up Dockerfile to reduce image size

constraint/pkg/regorewriter/ast_helpers.go, constraint/pkg/regorewriter/regorewriter.go
The logging was pretty much all at Info which caused way too much log
spam. This change moves the log statements to V levels 1 and 2.
=> Fix logging in regorewriter.

constraint/pkg/client/crd_helpers.go
Users without the appropriate cluster-level permissions receive errors like this when running `kubectl get all`:
```
Error from server (Forbidden): k8srequiredlabels.constraints.gatekeeper.sh is forbidden: User "user" cannot list resource "k8srequiredlabels" in API group "constraints.gatekeeper.sh" at the cluster scope
```
As far as I know, there are no other cluster-scoped resources in the all category, so constraints don't belong there either.
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-cli/kubectl-conventions.md#rules-for-extending-special-resource-alias---all
=> remove constraints from the 'all' category

constraint/deploy/tools.go
Add a build tag gated "tools" package to allow a dependent to vendor constraint template manifests using the standard go toolchain.
The standard `go mod vendor` command will prune non-go packages as described in https://github.com/golang/go/issues/26366.
We can cause a directory to be a go package by including a conditionally compiled go source file that does nothing.
This trick is documented [here](https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module).
Subsequently, a dependent module can vendor our manifests using a similar trick:
```
// +build tools
package tools
import _ "github.com/open-policy-agent/frameworks/constraint/deploy"
```
Closes #84
Signed-off-by: Oren Shomron <shomrono@vmware.com>
=> Support external vendoring of manifests using go toolchain

constraint/.golangci.yaml, constraint/Makefile, constraint/pkg/client/backend.go, constraint/pkg/client/client.go, constraint/pkg/client/client_test.go, constraint/pkg/client/drivers/local/local.go, constraint/pkg/client/drivers/remote/httpclient.go, constraint/pkg/client/drivers/remote/remote.go, constraint/pkg/client/e2e_tests.go, constraint/pkg/client/errors.go, constraint/pkg/client/probe_client.go, constraint/pkg/regorewriter/doc.go, constraint/pkg/regorewriter/filepath.go, constraint/pkg/types/validation.go
=> Allow users to get/delete templates by name only

constraint/pkg/client/client.go, constraint/pkg/client/client_test.go, constraint/pkg/client/rego_helpers.go, constraint/pkg/client/rego_helpers_test.go
Previously the client implemented internal checks to catch syntactic
mistakes with certain rules (e.g,. `violation`,
`matching_constraints`, etc.) With
https://github.com/open-policy-agent/opa/pull/2579 we are changing the
ast.Array type to pave the way for improved performance. This commit
preemptively updates the constraint framework to remove the dependency
on ast.Array. Note, the checks that have been removed were only
best-effort because rules are free to include variables in the
head/key. The checks have been simplified to just look for required
rules (i.e., the key is ignored.)
Signed-off-by: Torin Sandall <torinsandall@gmail.com>
=> pkg/client: Remove rule 'arity' check

constraint/pkg/client/crd_helpers.go, constraint/pkg/client/crd_helpers_test.go
This PR provides an answer for https://github.com/open-policy-agent/gatekeeper/issues/760
Adds a label gatekeeper.sh/constraint=yes for crds created for constrainttemplates.
```
$ kubectl get crd --show-labels  
NAME                                                 CREATED AT             LABELS  
configs.config.gatekeeper.sh                         2020-09-18T03:32:31Z   gatekeeper.sh/system=yes  
constraintpodstatuses.status.gatekeeper.sh           2020-09-18T03:32:31Z   gatekeeper.sh/system=yes  
constrainttemplatepodstatuses.status.gatekeeper.sh   2020-09-18T03:32:31Z   gatekeeper.sh/system=yes  
constrainttemplates.templates.gatekeeper.sh          2020-09-18T03:32:31Z   controller-tools.k8s.io=1.0,gatekeeper.sh/system=yes  
k8simageregistry.constraints.gatekeeper.sh …
```
=> Label constraint CRDs to query them more easily 

constraint/pkg/client/crd_helpers.go, constraint/pkg/client/crd_helpers_test.go
A user may use kubectl get contraint or get constraints to retrieve all the
crds generated by templates.
Fixes the second item discussed in https://github.com/open-policy-agent/gatekeeper/issues/677 (plus, this will need to be consumed)
=> Add a new category "constraints" to the generated CRDs.

constraint/pkg/client/crd_helpers.go, constraint/pkg/client/crd_helpers_test.go
This PR provides an answer for https://github.com/open-policy-agent/gatekeeper/issues/760
Mirrors all the labels from the constrainttemplate into the crd.
Will update the go mod in the gatekeeper repo once this is merged.
Signed-off-by: luckoseabraham <luckose4u@gmail.com>
=> mirror labels from constraint templates into crd

constraint/pkg/apis/addtoscheme_templates_v1alpha1.go, constraint/pkg/apis/addtoscheme_templates_v1beta1.go, constraint/pkg/apis/templates/v1alpha1/constrainttemplate_types_test.go, constraint/pkg/apis/templates/v1alpha1/register.go, constraint/pkg/apis/templates/v1beta1/constrainttemplate_types_test.go, constraint/pkg/apis/templates/v1beta1/register.go, constraint/pkg/client/crd_helpers.go
- fixes AddToScheme so autogenerated conversions are used
- removes unnecessary conversion between JSONSchemaProps and template OpenAPIV3Schema
=> Fix addtoscheme

constraint/README.md
Clarify that Client is not literally a golang interface.
Signed-off-by: Bryce Cronkite-Ratcliff <brycecr@google.com>
=> Minor updates to the constraint/README.md

constraint/Dockerfile
This fixes the unit tests, which are currently broken.
Somehow, I was able to merge my previous PR
(open-policy-agent/frameworks#114) with these tests broken.  They passed
in the GitHub actions, but are failing for me when I run them locally
(without the change in this PR).  I'm not sure how that happened.
I tried upgrading all the way to controller-runtime 3.0.0, but the
developers of that seem to have changed the way the package is
delivered.  Now, only the binary seems to available for download,
instead of a folder full of binaries.  Notably, this leaves out the
binaries for the API server components (etcd, for example) that are used
during unit test runs.
Signed-off-by: juliankatz <juliankatz@google.com>
=> Upgrade kubebuilder in test image to 2.3.2

constraint/config/crds/templates.gatekeeper.sh_constrainttemplates.yaml, constraint/deploy/crds.yaml, constraint/pkg/apis/templates/v1beta1/constrainttemplate_types.go
A Gatekeeper e2e test is currently failing in
open-policy-agent/gatekeeper#1286 due to the use of the `operations`
field.  This field is added by Gatekeeper, under a ConstraintTemplate's
`byPodsStatus`.  This field relied on the v1beta1 CRD behavior, where
unknown fields are preserved by default.
As this field fundamentally has to do with gatekeeper, it's better not
to define it in the Constraint Framework.  Other CF consumers have no
need for the Operations field.
Even better, we may eventually define ConstraintTemplateSpec in
Constraint Framework consumers, rather than in the library itself.
For now, adding `x-kubernetes-preserve-unknown-fields: true` to
ByPodStatus will solve our problem and maintain the existing behavior.
Signed-off-by: …
=> Preserve unknown fields in ByPodStatus

constraint/config/crds/templates.gatekeeper.sh_constrainttemplates.yaml, constraint/deploy/crds.yaml, constraint/pkg/apis/templates/v1alpha1/constrainttemplate_types.go, constraint/pkg/apis/templates/v1beta1/constrainttemplate_types.go
The previous PR (#117) put the `x-kubernetes-preserve-unknown-fields:
true` key/value pair one level too deep.  This moves it alongside
`byPodStatus`' `properties`.
Signed-off-by: juliankatz <juliankatz@google.com>
=> Move `x-kub...` alongside byPodStatus `properties`

constraint/pkg/client/client_test.go, constraint/pkg/client/crd_helpers.go, constraint/pkg/client/crd_helpers_test.go, constraint/pkg/client/e2e_tests.go, constraint/pkg/client/test_handler.go
This PR upgrades the Constraint Framework client to use the
apiextensionsv1 library for handling CRDs.  This is necessary for
supporting k8s 1.22, where apiextensionsv1beta1 CRDs are removed.
Crucially, this change switches CF to use the v1 CRD defaulting
functions, which do not set Spec.PreserveUnknownFields.  This field set
to true by default in v1beta1 CRD, but is disallowed in v1 CRD.  This
was preventing me from doing the same apiextensionsv1beta1 -->
apiextensionsv1 upgrade in Gatekeeper.
Signed-off-by: juliankatz <juliankatz@google.com>
=> Upgrade the CF client to apiextensionsv1

constraint/pkg/client/crd_helpers.go, constraint/pkg/client/crd_helpers_test.go
Gatekeeper adds the byPod field to the status of a Constraint once it is
applied to the cluster.  This previously relied on the preservation of
unknown fields by the API server.  As we are now applying Constraint kind
CRDs as v1 CRDs, this behavior breaks.
This PR adds an empty `status` to the Constraint kind's CRD's schema.
That status includes the `x-kubernetes-preserve-unknown-fields: true`
key/value pair, retaining the existing Gatekeeper functionality.
Signed-off-by: juliankatz <juliankatz@google.com>
=> Add x-preserve... to Constraint kind status

constraint/Makefile, constraint/pkg/apis/templates/transform.go, constraint/pkg/apis/templates/transform_test.go, constraint/pkg/apis/templates/v1alpha1/constrainttemplate_types.go, constraint/pkg/apis/templates/v1alpha1/constrainttemplate_types_test.go, constraint/pkg/apis/templates/v1alpha1/conversion.go, constraint/pkg/apis/templates/v1alpha1/zz_generated.conversion.go, constraint/pkg/apis/templates/v1beta1/constrainttemplate_types.go, constraint/pkg/apis/templates/v1beta1/constrainttemplate_types_test.go, constraint/pkg/apis/templates/v1beta1/conversion.go, constraint/pkg/apis/templates/v1beta1/zz_generated.conversion.go
Previously, I left ConstraintTemplate (CT) versions v1alpha1 and v1beta1
using apiextensionsv1beta1.JSONSchemaProps.  I thought this appropriate,
given that was what they were previously implemented as.  v1 CT, on the
other hand, would use v1beta1 JSONSchemaProps.
This turns out to be a bad idea.
Any logic we write that interacts with OpenAPIV3Schema in a CT's
Validation section is forced to interact with OpenAPIV3Schema's type.
Before this PR, that type is apiextensionsv1beta1.JSONSchemaProps.  This
makes our life difficult, as v1 CT's version of this variable will have
a different type.  This would then require us to re-implement any logic
for this section to implement a second type, or to do some gross
conversions.
Further, apiextensionsv1beta1 will be removed from …
=> ConstraintTemplate versions use apiextensionsv1

constraint/Makefile, constraint/config/crds/kustomization.yaml, constraint/deploy/crds.yaml, constraint/pkg/client/crd_helpers.go
Our CRDs were previously of version v1beta1.  In v1beta1,
spec.PreserveUnknownFields defaulted to `true`.  As we did not set this
value explicitly, the value was set to `true`.
We've now updated our CRDs to v1.  In v1, spec.PreserveUnknownFields
defaults to false.  In fact, it is being deprecated in favor of the more
targeted x-kubernetes-preserve-unknown-fields field.
Despite this new default, spec.PreserveUnknownFields remains `true` for
our CRDs, even after applying the new v1 versions.  This does not cause
any bad behavior, but is incorrect.  The simple fix is to set
spec.PreserveUnknownFields to false in all our CRDs.
As the Constraint kind CRD is generated in code, I've added this field
in constraint/pkg/client/crd_helpers.go.
The ConstraintTemplate CRD is generated using …
=> Set PreserveUnknownFields: false in v1 CRDs

constraint/config/crds/templates.gatekeeper.sh_constrainttemplates.yaml, constraint/deploy/crds.yaml, constraint/pkg/apis/templates/v1/constrainttemplate_types.go, constraint/pkg/apis/templates/v1/constrainttemplate_types_test.go, constraint/pkg/apis/templates/v1/conversion.go, constraint/pkg/apis/templates/v1alpha1/constrainttemplate_types.go, constraint/pkg/apis/templates/v1alpha1/constrainttemplate_types_test.go, constraint/pkg/apis/templates/v1alpha1/conversion.go, constraint/pkg/apis/templates/v1beta1/constrainttemplate_types.go, constraint/pkg/apis/templates/v1beta1/constrainttemplate_types_test.go, constraint/pkg/apis/templates/v1beta1/conversion.go
To handle legacy (pre-v1) CRDs, we inject
x-kubernetes-preserve-unknown-fields
in order to preserve the legacy behavior
that unknown fields were not pruned by the API
server.
Unfortunately, we are not handling the case
where no parameters are provided, which currently
means that parameters will be stripped from users' CRs.
This fixes that.
Fixes: https://github.com/open-policy-agent/gatekeeper/issues/1468
=> Inject empty `parameters` field for legacy schemas

.github/workflows/gatekeeper.yml
add a test that vendors current branch frameworks to Gatekeeper and runs tests
=> add gatekeeper test

constraint/pkg/client/errors.go
For decoupling frameworks and gatekeeper error handling
(which allows using go113 error conventinos in tests), I need to remove
the dependence of gatekeeper on error types defined in frameworks so
these may be changed safely to raw errors (where reasonable to do so).
As an intermediate, I'm adding this function so that gatekeeper can
continue to compile, and the implementation of this method may be
switched out in frameworks.
Signed-off-by: Will Beason <willbeason@google.com>
=> Provide IsUnrecognizedConstraintError

constraint/pkg/client/client_addtemplate_bench_test.go
Add benchmarks for client.AddTemplate for a simple ConstraintTemplate and a complex one. The complex ConstraintTemplate is a copy of [UniqueIngressHost](https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/uniqueingresshost/template.yaml). It's okay if this falls out of sync with the ConstraintTemplate it's based on - what matters is having a complex CT, not that it exactly matches one.
```
constraint$ go test ./pkg/client --bench=. --benchmem
goos: linux
goarch: amd64
pkg: github.com/open-policy-agent/frameworks/constraint/pkg/client
cpu: Intel(R) Xeon(R) W-2135 CPU @ 3.70GHz
BenchmarkClient_AddTemplate/Simple/1_Templates-12         	     129	   9058282 ns/op	 1200880 B/op	   23595 allocs/op
BenchmarkClient_AddTemplate/Simple/2_Templates-12 …
```
=> Add benchmarks for client.AddTemplate

constraint/pkg/apis/templates/v1/constrainttemplate_types_test.go, constraint/pkg/apis/templates/v1alpha1/constrainttemplate_types_test.go, constraint/pkg/apis/templates/v1beta1/constrainttemplate_types_test.go, constraint/pkg/client/backend.go, constraint/pkg/client/backend_test.go, constraint/pkg/client/client.go, constraint/pkg/client/client_opts.go, constraint/pkg/client/client_test.go, constraint/pkg/client/crd_helpers.go, constraint/pkg/client/crd_helpers_test.go, constraint/pkg/client/error_map.go, constraint/pkg/client/errors.go, constraint/pkg/client/query_opts.go, constraint/pkg/client/rego_helpers.go, constraint/pkg/client/rego_helpers_test.go, constraint/pkg/core/constraints/constraints.go, constraint/pkg/core/constraints/constraints_test.go, constraint/pkg/schema/transform.go, constraint/pkg/schema/transform_test.go, constraint/pkg/types/validation.go, constraint/pkg/types/validation_test.go
Move pkg/client to use go113 errors conventions.
In general, move to using constant base errors and wrap them with fmt.Errorf. Also make tests check that the expected error is returned.
In many cases I've extended tests to make them more flexible to accommodate this. I've made the tests more flexible, but haven't added examples of using that flexibility (for example, a client working with multiple targets). I intend to do so in a separate PR.
Fix a few concurrency bugs - the RW mutex wasn't properly guarding writes vs. reads for constraints. Also consider two Constraints with empty Specs to be "Semantically equal" as it is valid for Constraints to have empty specs.
=> Go113errors

constraint/pkg/apis/templates/v1/constrainttemplate_types_test.go, constraint/pkg/apis/templates/v1alpha1/constrainttemplate_types_test.go, constraint/pkg/apis/templates/v1beta1/constrainttemplate_types_test.go, constraint/pkg/client/backend.go, constraint/pkg/client/client.go, constraint/pkg/client/client_addtemplate_bench_test.go, constraint/pkg/client/client_test.go, constraint/pkg/client/drivers/interface.go, constraint/pkg/client/drivers/local/local.go, constraint/pkg/client/drivers/local/local_benchmark_test.go, constraint/pkg/client/drivers/local/local_test.go, constraint/pkg/client/drivers/local/local_unit_test.go, constraint/pkg/client/drivers/remote/remote.go, constraint/pkg/client/drivers/remote/remote_test.go, constraint/pkg/client/e2e_test.go, constraint/pkg/client/regolib/rego_test.go
Eliminate all uses of context.TODO(). Eliminate all uses of
context.Background() in production code. In all cases, either our
callers have a Context they can pass or the k8s framework provides one.
Remove unnecessary uses of context.Context. In quite a few places we
require context.Context, but nothing actually consumes it so it's just an
unused parameter that pollutes call sites and gives the false impression
that these requests are cancellable/etc. I've removed usages of Context
in these cases.
This change breaks gatekeeper - since this modifies our external APIs,
making this in a non-breaking way would require 5 PRs instead of 2. Once
this PR has been submitted, I'll submit a PR which updates the version
of frameworks/ that gatekeeper uses and fix the resulting breakages. …
=> Use context consistently

constraint/pkg/client/drivers/local/args.go, constraint/pkg/client/drivers/local/local.go, constraint/pkg/client/e2e_test.go
While playing around with the Gator CLI today I noticed
that I couldn't use the new print built-in from OPA in that
context. This function is really useful to quickly be able to
debug values of rules and variables, and would be a nice
addition to the Gator CLI (and possibly to the Gatekeeper
server too, but others can decide that). This PR adds options
to the local driver for enabling print and for providing a
printHook that decides where the output of print calls should
go. Will submit another PR for support in Gator if/when this
is merged.
Signed-off-by: Anders Eknert <anders@eknert.com>
=> Add support for print built-in

constraint/pkg/client/client_test.go, constraint/pkg/client/targethandler.go, constraint/pkg/client/test_handler.go, constraint/pkg/core/constraints/constraints.go, constraint/pkg/core/constraints/constraints_test.go
The idea here is that we can cache the golang match criteria for each
Constraint, rather than parsing it out each time. This PR does not actually implement the behavior; it just defines the interface so that we can start using it in Gatekeeper.
Also fix bug in SemanticEqual where one Constraint has Object defined
and the other does not.
Signed-off-by: Will Beason <willbeason@google.com>
=> Add ToMatcher to TargetHandler

constraint/pkg/regorewriter/errors.go, constraint/pkg/regorewriter/regorewriter.go, constraint/pkg/regorewriter/regorewriter_test.go, constraint/pkg/regorewriter/test/test_ok.rego
Increase unit test coverage for constraint/pkg/regorewriter #157
=> Add unit tests for regowriter

constraint/pkg/client/drivers/local/local.go
Fixes https://github.com/open-policy-agent/frameworks/issues/191
* Set `Content-Type` header for `external_data` request
cc: @sozercan 
Signed-off-by: Joel Kamp <joel.kamp@invitae.com>
=> fix: Content-Type header for external_data request

constraint/pkg/client/client.go, constraint/pkg/client/client_addconstraint_bench_test.go, constraint/pkg/client/client_audit_benchmark_test.go, constraint/pkg/client/client_review_benchmark_test.go, constraint/pkg/client/client_test.go, constraint/pkg/client/clienttest/cts/constraints.go, constraint/pkg/client/clienttest/cts/opts.go, constraint/pkg/client/drivers/interface.go, constraint/pkg/client/drivers/local/args.go, constraint/pkg/client/drivers/local/local.go, constraint/pkg/client/drivers/local/local_unit_test.go, constraint/pkg/client/drivers/remote/remote.go, constraint/pkg/client/e2e_test.go, constraint/pkg/client/errors/errors.go
Signed-off-by: Becky Huang <beckyhd@google.com>
=> Provide driver AddConstraint and RemoveConstraint (#170)

constraint/pkg/client/client_addtemplate_bench_test.go, constraint/pkg/client/client_test.go, constraint/pkg/client/clienttest/templates.go, constraint/pkg/client/drivers/local/compilers.go, constraint/pkg/client/drivers/local/driver.go, constraint/pkg/client/drivers/local/rego.go
Instead of using a variable template-specific location for libraries, use a fixed location so that users can refer to libraries by _either_ their fully qualified name _or_ their local name.
This behavior didn't have a complex enough test to trigger a bug found in Gatekeeper while merging the compiler sharding PR. This fixes the bug and adds a sufficiently-complex ConstraintTemplate which triggers the library import bug.
=> Make library prefix constant

constraint/pkg/client/drivers/local/args.go, constraint/pkg/client/drivers/local/builtin.go, constraint/pkg/client/drivers/local/driver.go, constraint/pkg/externaldata/request.go
Eliminating code duplication by exporting the external data default send request function so that we don't have to define the same function in gatekeeper.
Related PR: https://github.com/open-policy-agent/gatekeeper/pull/1891
=> feat: export external data default send request function

.github/workflows/workflow.yml
=> chore: bump golangci-lint version to 1.45.2

constraint/pkg/client/clienttest/templates.go, constraint/pkg/client/e2e_test.go, constraint/pkg/regorewriter/ast_helpers.go, constraint/pkg/regorewriter/regorewriter.go
Also add e2e tests that prove future works.
Signed-off-by: Will Beason <willbeason@google.com>
=> feat: Add support for future keyword

.github/workflows/workflow.yml
we added race conditions for unit tests, looks like we are hitting timeout
=> chore: increase gatekeeper test timeout

constraint/pkg/client/client.go, constraint/pkg/client/client_test.go, constraint/pkg/client/drivers/local/driver.go, constraint/pkg/client/template_client.go
Constraint status is ephemeral and callers should not be relying on our
cached version of the status field. Also, status can be very large, and
caching it wastes space.
Note that the Driver already drops `status` as it only preserves `spec.parameters`.
Signed-off-by: Will Beason <willbeason@google.com>
Fixes #209
=> perf: Don't cache Constraint status

constraint/pkg/client/client_test.go, constraint/pkg/client/drivers/local/driver.go, constraint/pkg/client/drivers/local/driver_unit_test.go, constraint/pkg/client/drivers/local/rego.go
Fixes https://github.com/open-policy-agent/gatekeeper/issues/2026
=> Make sure that the Rego hook is well-behaved with no data cache

constraint/pkg/apis/constraints/apis.go, constraint/pkg/client/client_test.go, constraint/pkg/client/crds/validate.go
This is so that "gator verify" tests may check the schema of
Constraints. We need an error specific to schema validation so users can
explicitly test for this case.
Required for https://github.com/open-policy-agent/gatekeeper/issues/1989
=> Add Constraint schema validation error

constraint/pkg/client/drivers/local/driver_unit_test.go, constraint/pkg/client/drivers/local/rego.go, constraint/pkg/client/drivers/local/storages.go
This is a possible fix for https://github.com/open-policy-agent/gatekeeper/issues/2283
Digging through the OPA code, the `with` statement triggers a deepcopy of the referenced data. With the new execution model implemented for performance improvements, this deepcopy would be run multiple times, which could mean significant CPU overhead and unnecessary memory usage.
Not using the `with` key would make it harder to mask out only resources in specific namespaces if we ever create namespace-scoped constraint templates, but should not hurt near-term functionality.
It may be we will need an alternative method for accessing the data cache if we need to mask visibility in the future.
=> perf: Remove `with` statement to avoid deepcopying data.inventory

.github/workflows/workflow.yml, constraint/Dockerfile, constraint/Makefile
=> ci: remove kubebuilder dependency

constraint/pkg/client/e2e_test.go, constraint/pkg/types/validation.go
If a review doesn't match a constraint's match spec AND tracing is enabled, then we print `TRACE: TRACING DISABLED`. This can confuse consumers because they specifically turn on tracing. We should only print this message if there are results and the trace is nil. See non test changes for in code comments too.
=> rework tracedump msg

constraint/pkg/client/client.go, constraint/pkg/client/client_test.go, constraint/pkg/client/clienttest/cts/constraints.go, constraint/pkg/client/template_client.go
Fixes https://github.com/open-policy-agent/frameworks/issues/326.
Fixes https://github.com/open-policy-agent/frameworks/issues/70.
Inject any defined default parameters from the ConstraintTemplate schema definition in a Constraint that does not define its parameters.
=> fix: default params for open api

.github/workflows/gatekeeper.yml
I think this is needed since we updated the `go.mod` in https://github.com/open-policy-agent/gatekeeper/pull/2538#discussion_r1189187165
=> Update gatekeeper.yml to use go version 1.20

constraint/pkg/client/client_test.go, constraint/pkg/client/clienttest/cts/constraints.go, constraint/pkg/client/clienttest/cts/opts.go, constraint/pkg/client/clienttest/templates.go, constraint/pkg/client/crds/crds_test.go, constraint/pkg/client/crds/validate.go, constraint/pkg/client/template_client.go, constraint/pkg/handler/handlertest/handler.go
This patch adds validation for unknown fields for a Custom Resource (CR) according to its schema.
This extra validation now requires that we update the test handler and test clients to comply with said validation.
=> feat: validate unknown fields for CR

constraint/pkg/client/drivers/k8scel/transform/cel_snippets.go, constraint/pkg/client/drivers/k8scel/transform/cel_snippets_test.go
variables.anyObject isn't recognized in-process until this is merged.
=> fix: `anyObject` was not fully plumbed to compiler, streamline plumbing to fix

constraint/pkg/client/client.go
Fix: https://github.com/open-policy-agent/gatekeeper/issues/3772
=> targetEnforcementAction key should take care of the object kind
