open-policy-agent/frameworks

- constraint/Gopkg.lock
- constraint/Gopkg.toml
- constraint/config/crds/templates_v1alpha1_constrainttemplate.yaml
- constraint/pkg/client/backend.go
- constraint/pkg/client/client.go
- constraint/pkg/client/crd_helpers.go
- constraint/pkg/client/crd_helpers_test.go
- constraint/pkg/client/drivers/interface.go
- constraint/pkg/client/drivers/remote/remote.go
> Add constraint endpoints

- constraint/Gopkg.lock
- constraint/pkg/client/backend.go
- constraint/pkg/client/client.go
- constraint/pkg/client/rego_helpers.go
- constraint/pkg/client/rego_helpers_test.go
- constraint/pkg/client/regolib/rego_test.go
- constraint/pkg/client/regolib/src.go
- constraint/pkg/client/regolib/templates.go
> Add client initialization logic

- constraint/pkg/client/backend.go
- constraint/pkg/client/client.go
- constraint/pkg/client/drivers/interface.go
- constraint/pkg/client/drivers/local/local.go
- constraint/pkg/client/drivers/local/local_test.go
- constraint/pkg/client/drivers/remote/remote.go
> Add local driver

- constraint/README.md
- constraint/pkg/client/client.go
- constraint/pkg/client/client_test.go
- constraint/pkg/client/e2e_tests.go
- constraint/pkg/client/regolib/src.go
- constraint/pkg/client/test_handler.go
> Separate create CRD action

- constraint/Makefile
- constraint/pkg/client/drivers/local/local.go
- constraint/pkg/client/regolib/src.go
> Use escaped paths for data

- .travis.yml
- Makefile
Signed-off-by: Torin Sandall <torinsandall@gmail.com>
> Add Travis CI configuration

- constraint/pkg/client/client.go
- constraint/pkg/client/client_test.go
- constraint/pkg/client/drivers/interface.go
- constraint/pkg/client/drivers/local/local.go
- constraint/pkg/client/drivers/local/local_test.go
- constraint/pkg/client/drivers/remote/remote.go
- constraint/pkg/client/e2e_tests.go
- constraint/pkg/client/test_handler.go
- constraint/tests/remote_test.go
> Allow traces on a per-request basis

- constraint/README.md
> Document tracing

- constraint/pkg/client/crd_helpers.go
This is to address https://github.com/open-policy-agent/gatekeeper/issues/123
on the Gatekeeper project.
> Make text of ConstraintTemplate no target error clearer

- constraint/README.md
- constraint/pkg/client/client.go
- constraint/pkg/client/drivers/local/local_test.go
- constraint/pkg/client/e2e_tests.go
- constraint/pkg/client/regolib/src.go
> Rename deny rule to violation

- constraint/pkg/client/client.go
- constraint/pkg/client/client_test.go
- constraint/pkg/client/crd_helpers_test.go
- constraint/pkg/client/rego_helpers.go
- constraint/pkg/client/rego_helpers_test.go
> Check to make sure templates have a violation rule defined

- constraint/README.md
- constraint/pkg/client/e2e_tests.go
- constraint/pkg/client/regolib/src.go
> Only pass parameters to ConstraintTemplate Rego source

- constraint/pkg/client/client_test.go
- constraint/pkg/client/crd_helpers.go
- constraint/pkg/client/crd_helpers_test.go
- constraint/pkg/client/e2e_tests.go
- constraint/pkg/client/regolib/src.go
- constraint/pkg/types/validation.go
> Add support for enforcementaction

- constraint/pkg/client/backend.go
- constraint/pkg/client/client.go
- constraint/pkg/client/client_test.go
- constraint/pkg/client/rego_helpers.go
- constraint/pkg/client/rego_helpers_test.go
> Add option to restrict allowed data fields

- constraint/pkg/client/rego_helpers.go
> Provide clearer error when access to the data document is disabled

- constraint/pkg/client/client.go
- constraint/pkg/client/client_test.go
- constraint/pkg/client/rego_helpers.go
> Do not allow empty Rego source strings on ConstraintTemplates

- constraint/pkg/regorewriter/ast_helpers.go
- constraint/pkg/regorewriter/filepath.go
- constraint/pkg/regorewriter/module.go
- constraint/pkg/regorewriter/regorewriter.go
- constraint/pkg/regorewriter/sources.go
* Update some variable names to make them fit with constraint template
nomenclature
* Add some docstrings.
> Clarify regorewriter module.

- constraint/pkg/client/client.go
- constraint/pkg/client/targethandler.go
Signed-off-by: Brian Thomas Kennedy <briankennedy@google.com>
> Add more docs to TargetHandler

- constraint/pkg/client/client.go
Fix a place where err didn't get checked.
> Fix error handling.

- constraint/README.md
> Document the new lib parameter

- constraint/go.mod
- constraint/pkg/client/crd_helpers.go
This addresses https://github.com/open-policy-agent/gatekeeper/issues/372
> Put constraints in the `constraint` category

- constraint/go.mod
- constraint/go.sum
- constraint/vendor/github.com/open-policy-agent/opa/topdown/trace.go
- constraint/vendor/modules.txt
> Upgrade to opa v0.16.2

- constraint/pkg/core/constraints/constraints.go
> Fixes SemanticEqual for constraint

- constraint/config/crds/templates_v1alpha1_constrainttemplate.yaml
- constraint/config/crds/templates_v1beta1_constrainttemplate.yaml
- constraint/deploy/crds.yaml
- constraint/pkg/apis/templates/v1alpha1/constrainttemplate_types.go
- constraint/pkg/apis/templates/v1alpha1/zz_generated.conversion.go
- constraint/pkg/apis/templates/v1beta1/constrainttemplate_types.go
- constraint/pkg/apis/templates/v1beta1/zz_generated.conversion.go
- constraint/pkg/core/templates/constrainttemplate_types.go
Signed-off-by: Emma McMillan <emma.mcmillan@microsoft.com>
> Update SyncedGeneration to ObservedGeneration

- constraint/config/crd_patch.yaml
- constraint/config/crds/templates_v1alpha1_constrainttemplate.yaml
- constraint/config/crds/templates_v1beta1_constrainttemplate.yaml
- constraint/deploy/crds.yaml
- constraint/pkg/client/crd_helpers.go
> Enable status subresource

- constraint/.golangci.yaml
> Fix golangci-lint memory usage

- constraint/pkg/client/crd_helpers.go
- constraint/pkg/client/crd_helpers_test.go
> Set maximum constraint name length to 63

- constraint/pkg/client/drivers/local/local.go
- constraint/pkg/client/drivers/local/local_test.go
Introduce `unsafeBuiltin` for driver to disable complier built-ins functions
> Toggle for OPA http.send #1137

- constraint/pkg/apis/templates/v1alpha1/constrainttemplate_types.go
- constraint/pkg/apis/templates/v1alpha1/zz_generated.conversion.go
- constraint/pkg/apis/templates/v1alpha1/zz_generated.deepcopy.go
- constraint/pkg/apis/templates/v1beta1/constrainttemplate_types.go
- constraint/pkg/apis/templates/v1beta1/zz_generated.conversion.go
- constraint/pkg/apis/templates/v1beta1/zz_generated.deepcopy.go
- constraint/pkg/core/templates/constrainttemplate_types.go
- constraint/pkg/core/templates/zz_generated.deepcopy.go
https://github.com/open-policy-agent/gatekeeper/issues/188
> Update API structs to not use slice of pointer.

- .github/workflows/gatekeeper.yml
- .github/workflows/workflow.yml
- constraint/.golangci.yaml
- constraint/Dockerfile
> chore: update linter action and go version

- constraint/pkg/client/drivers/rego/builtin.go
Fixes https://github.com/open-policy-agent/gatekeeper/issues/3119
> fix: fixes disable cache flow

- constraint/pkg/client/drivers/k8scel/transform/make_vap_objects.go
- constraint/pkg/client/drivers/k8scel/transform/make_vap_objects_test.go
fixes this error
> spec.matchConstraints: Required value
> fix: add matchConstraints to vap

- constraint/pkg/client/drivers/k8scel/transform/cel_snippets.go
- constraint/pkg/client/drivers/k8scel/transform/cel_snippets_test.go
This handles matchers in the case of DELETE. Technically it also handles cases where namespace/name changes, but that should not be possible.
> Run matchers against both object and oldObject

- .github/workflows/gatekeeper.yml
- .github/workflows/lint.yml
- .github/workflows/workflow.yml
- constraint/.golangci.yaml
- constraint/Dockerfile
- constraint/Makefile
- constraint/config/crds/externaldata.gatekeeper.sh_providers.yaml
- constraint/config/crds/templates.gatekeeper.sh_constrainttemplates.yaml
- constraint/deploy/crds.yaml
- constraint/pkg/client/drivers/rego/driver_unit_test.go
- constraint/pkg/externaldata/cache.go
- constraint/pkg/regorewriter/regorewriter.go
- constraint/pkg/regorewriter/regorewriter_test.go
- constraint/pkg/regorewriter/test/no-test/no-test-here
> chore: bump to go 1.22

- constraint/pkg/client/drivers/k8scel/driver.go
- constraint/pkg/client/drivers/k8scel/driver_test.go
This is necessary so that in-Gatekeeper VAP code evaluation behaves identically to in-K8s VAP code evaluation.
> fix: Unset Object on DELETE requests when using the VAP driver
